# Site settings
title: Protégé 5 Documentation
version: 5.0.0
email: protege@protege.stanford.edu
description: This is the documentation for Protégé 5.0.0.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://protegeproject.github.io/protege" # the base hostname & protocol for your site
twitter_username: protegeproject
github_username:  protegeproject
protege: Protégé
protver: Protégé 5.0.0

# Build settings
markdown: kramdown

collections:
  menus:
    output: true
    permalink: menus/:title/
  views:
    output: true
    permalink: views/:title/
